version: "3.2"
services:
  rabbitmq:
    build: ./docker/rabbitmq
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  mysql:
    image: mysql:5.7.12
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin -h 127.0.0.1 -P 3306 -u${MYSQL_USER} -p${MYSQL_PASSWORD} ping --silent
      interval: 10s
      retries: 60
  go:
    build: .
    container_name: 'go'
    depends_on:
      - rabbitmq
      - mysql
    links: [ "rabbitmq", "mysql" ]
    restart: always
volumes:
  mysql_data:
