version: "3.2"
services:
  rabbitmq:
    build: ./docker/rabbitmq
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  mysql:
    image: mysql:5.7.32
    container_name: mysql
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rabbitmq_go_net
  go:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: 'go'
    depends_on:
      - rabbitmq
      - mysql
    links: [ "rabbitmq", "mysql" ]
    restart: unless-stopped
    networks:
      - rabbitmq_go_net
volumes:
  mysql_data:
    driver: local
networks:
  rabbitmq_go_net:
    driver: bridge