version: "3.2"
services:
  rabbitmq:
    build: ./docker/rabbitmq
    container_name: 'rabbitmq'
    ports:
      - ${RB_QUEUE_PORT}:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  db:
    image: mariadb
    container_name: 'db'
    volumes:
      - ./data/mysql/${MYSQL_DATABASE}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306

networks:
  rabbitmq_go_net:
    driver: bridge